# FROM node:v18.16.0
# # Set the working directory to /app inside the container
# WORKDIR /App
# # Copy app files
# ENV PATH="./node_modules/.bin:$PATH"
# COPY . .
# # ==== BUILD =====
# # Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
# RUN npm install -g npm@^6.0.0
# # Build the app
# # RUN npm run build
# # ==== RUN =======
# # Set the env to "production"
# # ENV NODE_ENV production
# # Expose the port on which the app will be running (3000 is the default that `serve` uses)
# EXPOSE 3000
# # Start the app
# CMD [ "npm", "run", "dev" ]
# FROM node:carbon
# WORKDIR /App
# COPY package*.json ./
# RUN npm install
# COPY . .
# EXPOSE 8080
# CMD ["npm", "start"]
# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app inside the container
WORKDIR src/App

# Install an older version of npm that is compatible with Node.js v8.17.0
RUN npm install -g npm@6.14.15

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code to the container
COPY . .


# Set the command to start the application
CMD [ "npm", "start" ]

